### ISSUE TITLE
Progressive Web App

### ISSUE THREAD

**Issue by neeraj15022001** [saviomartin/loficlub#11]
**Is your feature request related to a problem? Please describe.**
Can be scaled by converting to Porgressive Web App

**Describe the solution you'd like**
Convert existing app into PWA

**Describe alternatives you've considered**
Cross Platform App but that will take lot of time, so we can leverage power of PWA to give user app like feel.

**Additional context**

**Comment by neeraj15022001** [comment]
I would like to work on this one

**Comment by saviomartin** [comment]
That's impressive @neeraj15022001 You can work on this 🙌
