### ISSUE TITLE
Security: exposed keys

### ISSUE THREAD

**Issue by MelkdeSousa** [saviomartin/loficlub#4]
**Firebase keys exposed**
This can be a serious security breach, since having access to these, a cascading effect of vulnerabilities can occur.

**Suggestion to solution**
The keys currently present in [src/backend.js](https://github.com/saviomartin/loficlub/blob/main/src/backend.js) must be stored in a separate file and using environment variables, the well-known `.env`.

**Attention**
Before deploying the new version, these variables present in `.env` must be declared locally within the platform, so that the application does not break down in production.

**Comment by parthpanchal123** [comment]
@saviomartin The API keys can be misused, so they must be separated out as environment variables as @MelkdeSousa pointed out. I can create a PR for the same.

**Comment by MelkdeSousa** [comment]
I'm doing this, @parthpanchal123 , but if you publish first, no problem

**Comment by parthpanchal123** [comment]
Ahh no problem go ahead , but just let @saviomartin see it first . Maybe he might have already started it .

**Comment by saviomartin** [comment]
Thanks a lot, @parthpanchal123 @MelkdeSousa, Thanks for letting me know. No prob, Happy to accept your PR

**Comment by parthpanchal123** [comment]
Seems I and @MelkdeSousa sent a PR for the same issue :laughing:

**Comment by MelkdeSousa** [comment]
🤣🤣🤣🤣
@saviomartin will decide on rock, paper, scissors

**Comment by saviomartin** [comment]
Yep, who's should I merge? 😅

**Comment by parthpanchal123** [comment]
@saviomartin Mine has a better description of the variables to be added along with the link showing where to add them on vercel page ! If that helps then go ahead with mine or else up to you :laughing:

**Comment by MelkdeSousa** [comment]
@parthpanchal123 is right, accept your PR, @saviomartin , no problem✌🏼😎

**Comment by saviomartin** [comment]
Thank you @MelkdeSousa for the PR! Appreciate it! Thanks a lot!
